In [7]:
import pandas as pd
sim_id = 1866912277
df1 = pd.read_parquet('../sim_results/median_17_year_holding_values.parquet').set_index('sim_id').loc[sim_id]

df2 = pd.read_parquet('../sim_results/max_holdings.parquet').set_index('date').drop('sim_id', axis = 1).sum(axis = 1)

In [51]:
import xarray as xr
df3 = pd.read_csv('../sim_results/sim_1866912277.csv').set_index('date').drop('sim_id', axis = 1).transpose()
df3 = df3.loc[[s for s in df3.index if s != 'GIC']]
data = xr.open_dataarray('../simulation_data/momentum.nc')
df_price = data.sel(band = 'price_end').to_pandas()
df_price = df_price.loc[[s for s in df3.index if s != 'GIC'], sorted(list(set(df3.columns).difference(['GIC'])))]

In [59]:
import numpy as np
x = (df3.values/df_price.values).flatten()
pd.Series(x - np.floor(x)).describe()

count    15028.000000
mean         0.023086
std          0.149262
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
dtype: float64

In [60]:
df2

date
2008-01-21    4.079860e+05
2008-02-18    4.079510e+05
2008-03-17    4.102178e+05
2008-04-14    4.117288e+05
2008-05-12    4.267016e+05
                  ...
2025-11-03    8.496300e+06
2025-12-01    8.686017e+06
2025-12-29    8.760233e+06
2026-01-26    9.040278e+06
2026-02-23    8.921764e+06
Length: 237, dtype: float64

In [20]:
df3

,date,ADC,ADM,APH,APO,APP,ARES,AZO,BKNG,BRK-B,...,VRT,VRTX,WM,WMT,WPC,XLG,XME,XOM,GIC,sim_id
0,2008-01-21,0.0000,12264.3936,0.0000,20395.6632,0.00,0.0000,0.0,0.0000,0.00,...,0.00,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,20363.0760,273133.683600,1866912277
1,2008-02-18,20096.1024,0.0000,0.0000,0.0000,0.00,0.0000,0.0,0.0000,0.00,...,0.00,0.00,0.0000,0.0000,0.0000,0.0000,20080.0044,13456.8973,267665.853900,1866912277
2,2008-03-17,0.0000,0.0000,0.0000,20058.5448,0.00,953.7000,0.0,0.0000,0.00,...,19.56,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,20037.5758,279499.468600,1866912277
3,2008-04-14,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0,0.0000,0.00,...,0.00,20331.50,0.0000,20339.2000,0.0000,0.0000,20320.8978,0.0000,253075.995900,1866912277
4,2008-05-12,0.0000,0.0000,21083.6521,21083.9466,0.00,0.0000,0.0,21073.9125,0.00,...,0.00,0.00,0.0000,0.0000,21077.7017,21082.1226,0.0000,0.0000,165410.139800,1866912277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2024-08-12,505166.7445,505206.2456,505183.2082,0.0000,342176.52,505178.9191,0.0,505081.3552,0.00,...,0.00,504922.37,0.0000,505195.4682,0.0000,0.0000,0.0000,0.0000,105.760653,1866912277
217,2024-09-09,0.0000,527813.3814,0.0000,527783.3030,453127.50,0.0000,0.0,527756.0563,0.00,...,0.00,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,527837.2253,-895.312447,1866912277
218,2024-10-07,468155.8982,563076.3545,0.0000,563118.0912,0.00,563014.8111,0.0,563011.2750,0.00,...,0.00,0.00,0.0000,563124.5406,0.0000,0.0000,0.0000,0.0000,-122.518947,1866912277
219,2024-11-04,572461.2144,572507.7040,0.0000,572413.8272,0.00,572375.2014,0.0,572380.6350,478115.49,...,0.00,0.00,572513.0024,572498.4320,0.0000,0.0000,0.0000,0.0000,-510.387147,1866912277
220,2024-12-02,0.0000,606593.8812,0.0000,0.0000,0.00,606495.3636,0.0,606622.8144,0.00,...,0.00,0.00,606432.1770,606614.0607,0.0000,0.0000,0.0000,606521.2492,592075.920553,1866912277

In [6]:
df2.columns

Index(['date', 'ADC', 'ADM', 'APH', 'APO', 'APP', 'ARES', 'AZO', 'BKNG',
       'BRK-B', 'BTAL', 'BTE', 'BX', 'CASY', 'COST', 'CTA', 'CVX', 'CWST',
       'CYA', 'DBMF', 'DECK', 'DOW', 'EGP', 'EXEL', 'FANG', 'FICO', 'FMF',
       'FR', 'GILD', 'IVOL', 'KKR', 'KLAC', 'KMLM', 'LLY', 'LMT', 'MCK',
       'MELI', 'META', 'MPC', 'MPWR', 'MSFT', 'NNN', 'O', 'ORLY', 'PFIX',
       'PGR', 'PLD', 'PSA', 'REXR', 'RSBT', 'RSG', 'SCHD', 'SCHG', 'STAG',
       'SVXY', 'TMUS', 'TRI', 'TRNO', 'TSLA', 'UNH', 'VOO', 'VRT', 'VRTX',
       'WM', 'WMT', 'WPC', 'XLG', 'XME', 'XOM', 'GIC', 'sim_id'],
      dtype='object', name='symbol')

In [9]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x = df1.index, y = df1.values, name = 'old'))
fig.add_trace(go.Scatter(x = df2.index, y = df2.values, name = 'old'))
fig.show()

In [82]:

df4 = pd.read_csv('../sim_results/sim_1866912277.csv').set_index('date').drop('sim_id', axis = 1)
df5 = pd.read_parquet('../sim_results/max_holdings.parquet').set_index('date').drop('sim_id', axis = 1).loc[df4.index]
df4 = pd.DataFrame(df4.values/df4.values.sum(axis = 1).reshape(df4.shape[0], 1), index = df4.index, columns = df4.columns)
df5 = pd.DataFrame(df5.values/df5.values.sum(axis = 1).reshape(df4.shape[0],1), index = df5.index, columns = df5.columns)
df4.index = pd.to_datetime(df4.index)
df5.index = pd.to_datetime(df5.index)
df4 = df4.loc[df4.index > pd.to_datetime('April 1, 2020')]
df5 = df5.loc[df5.index > pd.to_datetime('April 1, 2020')]

print(df4.mean(0).sort_values(ascending = False))
print(df4.mean(0).sort_values(ascending = False))

GIC     0.081103
FANG    0.041773
BKNG    0.036883
XOM     0.033384
ADM     0.032712
          ...
FMF     0.001288
CTA     0.000822
BTE     0.000820
CYA     0.000000
RSBT    0.000000
Length: 69, dtype: float64
GIC     0.081103
FANG    0.041773
BKNG    0.036883
XOM     0.033384
ADM     0.032712
          ...
FMF     0.001288
CTA     0.000822
BTE     0.000820
CYA     0.000000
RSBT    0.000000
Length: 69, dtype: float64

In [86]:
pd.concat([df4.iloc[1], df5.iloc[1]], axis = 1)

     2020-05-25  2020-05-25
ADC    0.000000    0.000000
ADM    0.000000    0.000000
APH    0.000000    0.050000
APO    0.050004    0.049996
APP    0.000000    0.000000
..          ...         ...
WPC    0.000000    0.000000
XLG    0.050008    0.000000
XME    0.000000    0.050000
XOM    0.000000    0.000000
GIC   -0.000037   -0.000044

[69 rows x 2 columns]